logging:
  config: classpath:logback-default.xml

spring:
  datasource:
    url: jdbc:mysql://mysql.hjgh.svc.cluster.local:33061/fy_boss?autoReconnect=true&allowMultiQueries=true
    username: app_common
    password: r|VR^Kmjv(Xw9wTbXGJ6U&?.@