spring:
  profiles:
    active: dev_fy

  datasource:
    url: jdbc:mysql://mysql.hjgh.svc.cluster.local:3306/fy_boss?autoReconnect=true&allowMultiQueries=true
    username: fy_user
    password: sw1KNlGx
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 300
    initialSize: 5
    maxWait: 60000
    minIdle: 5
    removeAbandoned: false
    removeAbandonedTimeout: 180
    logAbandoned: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 600000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  redis:
    host: redis.hjgh.svc.cluster.local
    port: 6379
    testOnBorrow: false
    testOnReturn: false
    password: gir##AcX
    jedis:
      pool:
      max-active: 300
      max-wait: 500
      max-idle: 300
      min-idle: 5

mode:
  debug: false

xzboss:
  openBroadband : CRM_TO_HSOP_OPEN_IMS_BROADBAND_001
  destoryBroadband : CRM_TO_HSOP_DESTORY_IMS_BROADBAND_001