spring:
  application:
    name: cloud-server

server:
  port: 4002

eureka:
  instance:
    hostname: server02.cluster.local
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 90 #定义服务失效的时间，默认90s
    lease-renewal-interval-in-seconds: 30 #定义服务续约任务的调用时间，默认30s
  client:
    register-with-eureka: true #false表示不向注册中心注册自己。
    fetch-registry: true #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索其他服务地址
    service-url:
      defaultZone: http://server01.cluster.local:4001/eureka/