spring:
  application:
    name: cloud-server

server:
  port: 4001

#spring-boot-starter-actuator相关配置
#management:
#  endpoints:
#    web:
#      exposure:
#        exclude:
#        include: "*" #暴露服务的所有信息端点，默认是info(应用的自定义信息，默认是空)、health(应用健康信息)
#info: #/actuator/info配置，默认为空
#  app:
#    version: 1.0.0
#    name: cloudServer

eureka:
  instance:
    hostname: server01.cluster.local
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 90 #定义服务失效的时间，默认90s
    lease-renewal-interval-in-seconds: 30 #定义服务续约任务的调用时间，默认30s
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索其他服务地址
    service-url:
      defaultZone: http://server02.cluster.local:4002/eureka/