server:
  port: 3305

zuul:
  routes:
    jbusine:
      path: /learn/busine/*
      serviceId: jbusine
      sensitiveHeaders:
      stripPrefix: false
    jbasics:
      path: /learn/jbasics/*
      serviceId: jbasics
      sensitiveHeaders:
      stripPrefix: false